//
// Created by EgrZver on 11.04.2023.
//

#ifndef CHECKERS_RESOURCES_H
#define CHECKERS_RESOURCES_H

#define IDB_TEST 10
#define IDI_APP_BIG_ICON 1
#define IDI_APP_WIN_ICON 2
#define IDB_BC_EMPTY_BLACK 3
#define IDB_BC_EMPTY_WHITE 4
#define IDB_BC_REG_BLACK 5
#define IDB_BC_REG_WHITE 6
#define IDB_BC_KING_BLACK 7
#define IDB_BC_KING_WHITE 8
#define IDB_BOARD_BORDER 12

#endif //CHECKERS_RESOURCES_H
