//
// Created by EgrZver on 11.04.2023.
//

#ifndef CHECKERS_RESOURCES_H
#define CHECKERS_RESOURCES_H


#define IDI_APP_BIG_ICON 1
#define IDI_APP_WIN_ICON 2

#define IDB_BC_EMPTY_BLACK 3
#define IDB_BC_EMPTY_WHITE 4
#define IDB_BC_REG_BLACK 5
#define IDB_BC_REG_WHITE 6
#define IDB_BC_KING_BLACK 7
#define IDB_BC_KING_WHITE 8
#define IDB_BOARD_TO_MOVE 9

#define IDB_BOARD_BORDER 12

#define IDB_BC_REG_BLACK_VICTIM 20
#define IDB_BC_REG_WHITE_VICTIM 21
#define IDB_BC_KING_BLACK_VICTIM 22
#define IDB_BC_KING_WHITE_VICTIM 23

#define IDB_BC_EMPTY_BLACK_SELECTED 33
#define IDB_BC_EMPTY_WHITE_SELECTED 34
#define IDB_BC_REG_BLACK_SELECTED 35
#define IDB_BC_REG_WHITE_SELECTED 36
#define IDB_BC_KING_BLACK_SELECTED 37
#define IDB_BC_KING_WHITE_SELECTED 38
#define IDB_BC_EMPTY_TO_MOVE_SELECTED 39

#define IDB_BC_REG_BLACK_VICTIM_SELECTED 50
#define IDB_BC_REG_WHITE_VICTIM_SELECTED 51
#define IDB_BC_KING_BLACK_VICTIM_SELECTED 52
#define IDB_BC_KING_WHITE_VICTIM_SELECTED 53

#endif //CHECKERS_RESOURCES_H
